#!mast .ruby .yardopts bin demo lib test [A-Z]*.*
.ruby
.yardopts
demo/account_example.md
demo/applique/dci.rb
lib/dci/context.rb
lib/dci/object.rb
lib/dci/role.rb
lib/dci.rb
COPYING.md
HISTORY.md
README.md
